### ISSUE TITLE
Add support for Entry.SetIconFromStock()

### ISSUE THREAD

**Issue by weberc2** [gotk3/gotk3#238]
This function remains to be bound.

**Comment by founderio** [comment]
`Entry.SetIconFromStock()` is implemented in [gtk_deprecated_since_3_10.go](https://github.com/gotk3/gotk3/blob/master/gtk/gtk_deprecated_since_3_10.go#L69) and only compiled for gtk versions before 3.10. If you absolutely need it, use the build tag `gtk_3_8` or `gtk_3_6`.
This might cause issues if you need more recent features.

Since stock icons have been deprecated it is highly suggested to use `Entry.SetIconFromIconName` unless you really, really need to use the deprecated stuff.

**Comment by founderio** [comment]
See #253
