### ISSUE TITLE
Windows 10 64-bit: Link.exe - running gcc failed in AppData\Local\Temp

### ISSUE THREAD

**Issue by Bresenham** [gotk3/gotk3#352]
I installed MinGW and GTK dependencies, the command

`go get github.com/gotk3/gotk3/gtk`

works without erros. But if I try to build a gtk-example like this:

`PS C:\Users\Standardbenutzer\go\src\github.com\gotk3\gotk3-examples\gtk-examples\fixed> go build`

I get:

`# github.com/gotk3/gotk3-examples/gtk-examples/fixed
D:\Programme\GoLang\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\STANDA~1\AppData\Local\Temp\go-link-175442247\go.o: file not recognized: File format not recognized`

If I take a look in my AppData\Local\Temp folder, there is no folder `go-link-175442247`?

Any help is greatly appreciated

**Comment by drakbar** [comment]
@Bresenham sounds like something is hosed on your system not sure what though.

I am pretty the reason you don't see `go-link-175442247` is because `go` uses the temp folder for dumping files during the build process, and then it cleans up after itself. You can open the explorer window in that folder and run `go build` on one of your projects and see it as it happens. Not saying that you will be able to fix it anyway by doing this, but just trying to give a little insight on whats happening behind the curtains.

**Comment by andre-hub** [comment]
@Bresenham 
You still have that problem?

Have you ever tried following the [instructions described in our Wiki](https://github.com/gotk3/gotk3/wiki/Installing-on-Windows)

**Comment by andre-hub** [comment]
There has been no feedback on whether the problem continues. I am therefore closing this issue until further notice. If there is still a need, please open this issue again and add a current problem description.
