### ISSUE TITLE
Can't install gotk3

### ISSUE THREAD

**Issue by JulienCHATEAU** [gotk3/gotk3#393]
Hello,
I wanted to install gotk3 with `go get github.com/gotk3/gotk3/gtk` command but it raised the error : 
`gotk3/gdk/gdk_since_3_20.go:11:16: could not determine kind of name for C.gdk_gl_context_is_legacy`

I am using Ubuntu bash terminal on Windows 10, I have go 1.12.7 and installed gtk, cairo and glib with `sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev`

Have you any idea to resolve this ?

**Comment by Bios-Marcel** [comment]
How exactly are you building your project? What version of GTK do you have? If you are biuilding with a lower version, you gotta apply the correct tags in order to tell the go compiler which files should actually compiles, as you can't compile file for 3.20 and more if you don't actually have that GTK version. I would assume that you run a ubuntu 18.04, so I thought libraries should be up-to-date enough.

See this for information on the tags: https://github.com/gotk3/gotk3/wiki#installation

**Comment by JulienCHATEAU** [comment]
I installed GTK as mentionned on your wiki but the apt package wasn't the last version, i had to get the latest on by myself. So, my project compiled with GTK 3.22 version as you said. I'll now have to deal with a display error when executing your examples but you solved my issue.
Thank you !

**Comment by Bios-Marcel** [comment]
I am assuming you try running the app via the WSL? Sadly that won't work, since there is no xserver,  as far as I know. You'd have to run an xserver on windows and tell the WSL about it, so it can use it to render applications.

Something like this: https://sourceforge.net/projects/vcxsrv/

**Comment by Bios-Marcel** [comment]
If you are on windows, you might just want to use msys/mingw instead of the wsl, so you can actually compile for windows.

**Comment by JulienCHATEAU** [comment]
You're right, there isn't any xserver on WSL. I installed Vcxsrv as you advised and it worked perfectly. The window of my project was oppened correctly but style looks weird. Buttons, entries and other widgets look different as they should be, maybe caused by a lot of these `Gtk-WARNING **: 19:53:06.361: Theme parsing error: [...]` errors.

**Comment by Bios-Marcel** [comment]
Well, can't help you those, i guess this issue is resolved then.
