### ISSUE TITLE
Is it possible to update to GTK+3.22 on Ubuntu 16.04?

### ISSUE THREAD

**Issue by daryl0505** [gotk3/gotk3#419]
I'm trying to update via gotk3:
`go get -tags gtk_3_18 github.com/gotk3/gotk3/gtk`

But just getting errors:
```
# github.com/gotk3/gotk3/gtk
../go/src/github.com/gotk3/gotk3/gtk/glarea.go:99: cannot use (*C.int)(unsafe.Pointer(&major)) (type *C.int) as type *C.gint in argument to _Cfunc_gtk_gl_area_get_required_version
../go/src/github.com/gotk3/gotk3/gtk/glarea.go:99: cannot use (*C.int)(unsafe.Pointer(&minor)) (type *C.int) as type *C.gint in argument to _Cfunc_gtk_gl_area_get_required_version
../go/src/github.com/gotk3/gotk3/gtk/glarea.go:107: cannot use C.int(major) (type C.int) as type C.gint in argument to _Cfunc_gtk_gl_area_set_required_version
../go/src/github.com/gotk3/gotk3/gtk/glarea.go:107: cannot use C.int(minor) (type C.int) as type C.gint in argument to _Cfunc_gtk_gl_area_set_required_version
```

**Comment by hfmrow** [comment]
> Is it possible to update to GTK+3.22 on Ubuntu 16.04?

Yes but really not easy since desktop environment depend on built in version ...

> I'm trying to update **via** gotk3

As far as the gotk3 problem is concerned, I hope you will not try to update your version of gtk 3.18 to 3.22 with.
Otherwise, these errors seem to be a version conflict, but I'm sorry, I can not help you.
When I was on 3.18 with 16.04, I never had this problem, while using the same command as you.
Try to ask the main owner of the project.
