### ISSUE TITLE
Can I contribute to the code documentation?

### ISSUE THREAD

**Issue by andraantariksa** [gotk3/gotk3#451]
The documentation on https://godoc.org/github.com/gotk3/gotk3/cairo#Context.SetSourceRGB are not clear enough. I just realize that the R, G, and B has a value ranged from 0.0 to 1.0.

Can I make a pull request to add a documentation about this?

**Comment by hfmrow** [comment]
When I need precision about argument of gtk3 / cairo / pango / gdk components, structure, variable, functions ... I found (most of time) the answer on the official documentation.
https://www.cairographics.org/manual/cairo-cairo-t.html#cairo-set-source-rgb

Your idea is good but documentation is dynamically extracted from the source code, so, to modify it, you need to change it. Not a good thing, since there is a risk of to much overload the source code with extra comments.

**Comment by andraantariksa** [comment]
Well, at least someone has to put the official docs as a reference...

**Comment by hfmrow** [comment]
>Well, at least someone has to put the official docs as a reference...

Yes, you may ask to the project owners.

I cannot put to the official docs as a reference, but, I can give you some basic references that I use if they can help you:

- [GTK3](https://developer.gnome.org/gtk3/stable/)
- [GDK3](https://developer.gnome.org/gdk3/stable/)
- [GLib](https://developer.gnome.org/glib/)
- [Pango](https://developer.gnome.org/pango/stable/)
- [Cairo](https://www.cairographics.org/documentation/)

_This list is not exhaustive._
