### ISSUE TITLE
something needs to be improved

### ISSUE THREAD

**Issue by eexpress** [gotk3/gotk3#469]
1. No devhelp support, each time I need grep in the mod directory to find how to write.

1. Seems no binding to `Properties` of Widgets, I want use `grid.ColumnSpacing = 5` instead of  `grid.SetColumnSpacing(5)`. 

1. Seems no binding to `Inherited Members`. It's hard to find how to write code with Parent Widgets. Eg, Gtk.Grid inherited from Gtk.Container which inherited from Gtk.Widget, I do not know how to modify Gtk.Widget.Margin (Gtk.Grid.Margin).

**Comment by founderio** [comment]
> No devhelp support, each time I need grep in the mod directory to find how to write.

https://godoc.org/github.com/gotk3/gotk3/gtk is as close as you will get. Feel free to contribute to the comments in source code to improve the documentation there.
Otherwise I can recommend the official GTK documentation, e.g. https://developer.gnome.org/gtk3/stable/GtkLabel.html and documentation of other wrappers. PyGTK has excellent documentation, you just need to guess the function names a bit.

> Seems no binding to Properties of Widgets

Correct, properties are not bound. You can use `something.GetProperty("has-selection").(bool)` and `something.SetProperty("has-selection", true)` as a workaround.
Accessing properties like `grid.ColumnSpacing = 5` will very likely never work in golang, simply because the language cannot do that. We'd have to intercept writes to a variable, or somehow sync, so not feasible. The closest you can get are getter and setter properties - either specialized `grid.SetColumnSpacing(5)` or generic `grid.SetProperty("column-spacing", 5)`.

> Seems no binding to `Inherited Members`

Inherited members, if there is a wrapper for them, are indeed supported. `something.SetProperty("has-selection", true)` is in fact inherited. The issue you see here is that `Margin` is not supported (no properties, see above..). As there are no "standard" accessor functions for the margin property you will need to use Get/SetProperty as described above.

**Comment by andre-hub** [comment]
meanwhile there are also [go pkg page](https://pkg.go.dev/github.com/gotk3/gotk3/gtk?tab=doc)
