### ISSUE TITLE
New tagged release planned?

### ISSUE THREAD

**Issue by mdhorn** [gotk3/gotk3#470]
I appreciate this great work for gotk3. 

There have been lots of great fixes and enhancements since the last tagged released.
```
GOTK3 Version 0.3.0
@andre-hub andre-hub released this on Jan 7 · 214 commits to master since this release
```

Any plans to tag a new release for those of us that prefer to stick to released/tested versions?
Or can we assume that the tip of the master has had some level of testing and is best practice to use that?

**Comment by andre-hub** [comment]
@mdhorn 
need you a specific version or releases?
e.g. every year one version?

CC: @Bios-Marcel  @MJacred @founderio @hfmrow @gotk3/gotk3-core

**Comment by mdhorn** [comment]
We are using this for our OS installer, so we prefer to build with "released" tagged versions rather than just the tip-of-master.  

Is the project running any sort of regressions/validation for pull requestion validation?
I was hoping there was some basic cadence similar to:
-  accepting PR for improvements, bug fixes, CVE fixes, etc
-  baseline validation regression
- cut a new release tag
Repeat

**Comment by MJacred** [comment]
I agree with @mdhorn that using release tags would be ideal.

Afaik, currently, `go test` is run for gtk 3.10, 3.18 and 3.22 in the travis pipeline. The number of unit tests is still relatively small, though

It would be nice to run some sanitizers (at least memory and leak); e.g.:  
https://github.com/google/sanitizers

**Comment by andre-hub** [comment]
@mdhorn @MJacred 
Well, in the last few years we got a lot of PR that the community needed and submitted. We have done our best to cause as few problems for other users as possible due to the changes. 

Meanwhile the code base is already relatively high, the community seems to be getting bigger, so we try to maintain an even higher quality assurance.

But there are no plans yet.

CC @Bios-Marcel

**Comment by founderio** [comment]
It would probably be a good idea to add a PR template which asks if there are breaking changes. A summary of those should be in the release notes for each release. Not new bindings, but things like switching from `*Widget` to `IWidget` and similar public API changes.

And maybe a check (automated in CI?) if the examples still compile? Might look into that.

If you want to think about a 1.0 Release - what would be the bare essentials? A few candidates:
* Usage of deprecated features?
* IWidget and other interfaces as return values?
* GValue implementation?
* Feature complete up to GTK 3.x?

**Comment by andre-hub** [comment]
i have added milestones

https://github.com/gotk3/gotk3/milestones

i think we create a next version with the actual functions and fix some open bugs for this.
in the future we map e.g. issues to milestones.

in the past we intentionally decided against interfaces for all gtk objects.

I think since the GTK version 3.22 is the last version of 3, this project could be complete to version 1.0 feature.

GTK 4 will then start separately.

is the issue closed or do you need more information?

**Comment by andre-hub** [comment]
@mdhorn can give us you feedback?

otherwise we close this issue  on 15.02.2020

**Comment by mdhorn** [comment]
I was mainly hoping a version to be tagged, "validated", and release on some cadence so we could build against a released version instead of grabbing the tip of master for building products.
Looks like this is being addressed by via milestone which I assume will then translate into a release.
