### ISSUE TITLE
Question: Should I use .Unref?

### ISSUE THREAD

**Issue by bergwerf** [gotk3/gotk3#473]
Since I do not know the specifics of GTK's memory management and the way the binding and Go deal with this, I was wondering if I should unref dialogs after they are closed. I do not keep any pointer to the dialog in the scope so I can imagine this is taken care of already.

Another slightly related question: I found a window becomes empty after the user closes it (a window created from a Glade template). So if I want to show it again I have to rebuild it. I am fine with this, but I was just wondering if this is intended behavior.

Dialog creation looks like this:
```go
func AlertError(title string, description string) {
	var win *gtk.Window
	signals := map[string]interface{}{
		"continue": func() {
			win.Close()
		},
	}

	ids := []string{"window", "title", "description"}
	obj := BuildGladeFile("ui/alert.glade", signals, ids)

	AsLabel(obj["title"]).SetText(title)
	AsLabel(obj["description"]).SetText(title)
	win = AsWindow(obj["window"])
	win.Show()
}
```

**Comment by founderio** [comment]
The way I understand this:  
`glib.Take` (which is used most of the time when GTK stuff enters "golang land") sets a finalizer to call `.Unref` for you, as soon as the garbage collector gets rid of the go wrapper.

`func (b *Builder) GetObject(name string) (glib.IObject, error)`, which I assume you are using, uses `glib.Take`. So it is safe to assume that you do not need to call `.Unref`, even if you retain pointers outside the scope.  
Further information for when finalizers are called: https://golang.org/pkg/runtime/#SetFinalizer

However, not every entry point in this project uses glib.Take and I'm not entirely certain if that is intentional or a result of organic growth of the codebase.

**Comment by bergwerf** [comment]
Aha, that makes sense. Sorry for my unclear example, I am indeed using `GetObject`.

So when `gtk.Window.Close` is called, does that cause all window content to be garbage collected/removed? (such that when I `.Show` is again later, it is empty).

**Comment by founderio** [comment]
afaik, window content is kept alive by the window itself until destroyed. As long as some reference is alive, stuff will not be removed (GTK handles that).

Which means: if stuff disappears when calling `gtk.Window.Close`, this is likely happening on GTK side.
It seems this is by design, but can be avoided: https://stackoverflow.com/questions/52518548/show-gtkapplicationwindow-after-close

Usage of `gtk_widget_hide_on_delete` is implemented in the wrapper layer like so:

```
func (v *Widget) HideOnDelete() {
	C._gtk_widget_hide_on_delete(v.native())
}
```

Which means for your example, calling `win.HideOnDelete()` once after building it, should keep your window content around.

Another note:
Careful, I have seen an instance of gtk.Application being garbage collected, due to the variable getting out of scope.
As this was the top-layer holding references to all of the application UI, things broke, causing strange crashes, as the garbage collector is not guaranteed to run consistently. So you should keep references to stuff you need (at least the top-most layer, i.e. Application or Window), but references you don't need anymore are taken care of by the wrapper layer.

**Comment by bergwerf** [comment]
Thanks for the additional explanation!
