### ISSUE TITLE
KeyVal() fails

### ISSUE THREAD

**Issue by Hultan** [gotk3/gotk3#542]
**Describe the bug**
When I try to catch key presses on the num pad, it works fine for all numbers between 1 and 9 with the exception of 4 and 6. I am writing a sudoku game so I am not interested in 0, but I am using divide, multiply and subtract also on the numpad and they also work.

**To Reproduce**
I am using the following code:
```
	win.Connect("key-press-event", func(window *gtk.Window, event *gdk.Event) {
		keyEvent := gdk.EventKey{Event: event}
		modifiers := uint(gtk.AcceleratorGetDefaultModMask())
		keyVal := keyEvent.KeyVal()   // <----  Error here, only when pressing num 4 or 6

                // Removed some irrelevant code
		} else if keyVal == gdk.KEY_KP_1 {
			s.KeyIsPressed(1)
			da.QueueDraw()

                ...

		} else if keyVal == gdk.KEY_KP_4 {
			s.KeyIsPressed(4)
			da.QueueDraw()

               ...

			da.QueueDraw()
		} else if keyVal == gdk.KEY_KP_6 {
			s.KeyIsPressed(6)
			da.QueueDraw()
               }
               ...
	})

```

**Expected behavior**
I am expecting the num 4 and num 6 keys to work like the other numbers.

**Error messages**
The keys 4 and 6 (on the num pad) gives me the following error, when calling keyEvent.KeyVal() function:

Failed to eval expression:  {
 "Expr": "keyEvent.State()",
 "Scope": {
  "goroutineID": 1,
  "frame": 0
 },
 "Cfg": {
  "followPointers": true,
  "maxVariableRecurse": 1,
  "maxStringLen": 64,
  "maxArrayValues": 64,
  "maxStructFields": -1
 }
} 

Eval error: function calls not allowed without using 'call'

**Environment:**
gtk3 version: 'Pamac says I have Gtk3 1:3.24.14+9+g429a6287e0-1. Is 3.24 the version number?'
go version: '1.14.'
os: 'Manjaro Cinnamon'
other stuff: ''
 
**Additional context**
I do not now if this is a Gotk3-problem, it might very well be a driver problem with my Microsoft Natural Ergonomic Keyboard, but all the numkeys are working perfectly in any text editor.

I also want to add that I am new to using Go and GTK and I am very unsure about the following row :
```keyEvent := gdk.EventKey{Event: event}```
After trial and error and searching the web for about an hour, I got it to "kind of" work this way, but I don't know if this is the correct way to "convert" an gdk.Event to a gdk.EventKey. I tried using the normal type conversion syntax (event.(*gdk.EventKey)?) but I never got that to work.

**Comment by MJacred** [comment]
yes. 3.24 is the GTK version

The problem lies with how you create your EventKey.

Please understand that gotk3 is a wrapper around gtk (which is coded in programming language C). So we often need to wrap stuff so it does not break. This involves lots of pointers. So whenever you use something from gotk3 and use your curly brackets on them `gtk.Whatever{Something: something}`, you'll likely run into problems.

this is how the wrapping needs to be, so that gotk3 can talk to gtk:
```go
func EventKeyNewFromEvent(event *Event) *EventKey {
	ee := (*C.GdkEvent)(unsafe.Pointer(event.native()))
	ev := Event{ee}
	return &EventKey{&ev}
}
```

Therefore, this is the proper way for you:
```go
keyEvent := gdk.EventKeyNewFromEvent(event)
```

An additional advice: C has the ability for inheritance. So GtkApplicationWindow, for example, inherits from GtkWindow. Go has no such inheritance.  
To make this missing inheritance as comfortable as possible, we write interfaces. For GtkWindow, for example, we have the struct `Window` and the interface `IWindow`. IWindow (and other cases like Widget and IWidget) have function definitions in the format of `ToWindow() *Window` (or `ToWidget() *Widget` for `Widget`).  
This means, don't use *gtk.Window (or *gtk.Widget) in your code whenever you create functions.
I suggest you replate:
* `func(window *gtk.Window, event *gdk.Event)` with
* `func(window gtk.IWindow, event *gdk.Event)`

In case you ever use that func you created on an gtk.ApplicationWindow, your program WILL crash.

**But please note**: funcs like `ToWindow()` have only been added recently. They are not available in gotk3 version 0.4.0. You'd need to use the master branch.

P.S.: You might want to avoid Go 1.14 for now. It made breaking changes to cgo (which is used to create the bindings/wrapper). There is another bug open which seems to come from Go 1.14

**Comment by Hultan** [comment]
Wow, I have a lot to learn about all of this. Thanks for all the great advice, I have to look into all of that asap. Sorry for blaming you guys for my bad code :-)

**Comment by Hultan** [comment]
Using ```keyEvent := gdk.EventKeyNewFromEvent(event)``` got rid of the error message, but 4 and 6 still does not work?

**Comment by MJacred** [comment]
Nah, don't worry, there is also some messy/hacky code there

> Question about *gtk.Window, does that apply to even to *gtk.Button and all other elements? So gtk.IWindow, gtk.IButton and so on?

Hm... gtk.Button has no `IButton` interface. You can still access the funcs of gtk.Bin, gtk.Container and gtk.Widget, though.  
So far, I haven't had any need for an interface to gtk.Button. Often, GTK (and gotk3) returns a Widget (*gtk.Widget for gotk3).  
If there is ever a need, then this can be added/changed.

**Comment by MJacred** [comment]
> Using `keyEvent := gdk.EventKeyNewFromEvent(event)` got rid of the error message, but 4 and 6 still does not work?

I have an ergonomic microsoft keyboard as well. the following code prints 1, 4 and 6 if I press them on my keyboard.  
Dumb question, but I'll ask anyway: 1 works? so your num lock is active?

```go
win.Connect("key-press-event", func(window gtk.IWindow, event *gdk.Event) {
	keyEvent := gdk.EventKeyNewFromEvent(event)
	keyVal := keyEvent.KeyVal()
	if keyVal == gdk.KEY_KP_1 {
		log.Println(1)
	} else if keyVal == gdk.KEY_KP_4 {
		log.Println(4)
	} else if keyVal == gdk.KEY_KP_6 {
		log.Println(6)
	}
})
```

**Comment by Hultan** [comment]
Yes, all other keys I have tried work, 1 through 9 and /,* and -, with the exception of 4 and 9.

By the way, the error message is still there, but apparently I only see it if I step through the code (with F10 using VS Code).

**I found the problem though**, I was using this line, in an earlier attempt to try and catch the CTRL key, when I removed that everything works fine. So again, my crappy code was the problem.

```modifiers := uint(gtk.AcceleratorGetDefaultModMask())```
