### ISSUE TITLE
[BUG] Unreferencing doesn't happen in the UI thread, which can lead to crashes

### ISSUE THREAD

**Issue by olabiniV2** [gotk3/gotk3#810]
In a larger applications we have started to see more and more unpredictable crashes. The one common feature of these is that the crash is generally a segmentation fault, and that two threads calling in to gotk3 C code is involved. The main UI thread is locked correctly using `runtime.LockOSThread()`. However, in the stack trace, another goroutine is running `Unref()` at the same time as a C function is called in the UI thread.

It seems likely that this crash is caused by a an unlikely combination of one object being freed, while the same memory is being accessed from the main UI thread. There are some indications of the same problem being the root cause of other problems, such as #797 and #630. 

The documentation for `runtime.SetFinalizer` is clear that all the finalizers will run sequentially in its own dedicated goroutine. This goroutine will always be separate from the UI thread. In a larger program with many GTK operations, you can likely reproduce this problem by repeatedly doing many actions while running `runtime.GC()` repeatedly.

**Comment by diamondburned** [comment]
Wouldn't the correct solution to this be to construct GTK objects in the main thread using `IdleAdd` instead?

**Comment by olabiniV2** [comment]
No, that's actually already happening. That's not the cause of the problem. The cause is that the finalizer will _always_ run in a different goroutine.

**Comment by diamondburned** [comment]
I'm still confused on the actual problem here. If C actually keeps the GObject past the C function call, then it should've called `g_object_ref` on the object, so Go `_unref`ing the object should not have caused it to free.

Both `g_object_ref` and `g_object_unref` are documented to be thread-safe functions, so Go calling the finalizers in different threads shouldn't have caused an issue, as long as the objects are used properly.

If a C function does not take the ownership of an object (and therefore does not call `g_object_ref`), then competent casting should've convinced the GC that the Go object is still needed on memory:

```go
func (obj *AnyObject) CMethod() {
    // Note that no uintptrs are handled around here. See below.
    C.anyobject_cmethod((*C.AnyObject)(obj.Object))
}
```

The only other case I could think of (but unsure if it's actually reasonable) is the library's use of `uintptr` in weird places, which might trick the GC into thinking that an object is done during a C function call, just because the C object was casted from a `uintptr` and not by directly accessing the Go `*Object` object (which has the finalizer attached).

**Comment by olabiniV2** [comment]
Hi,

To be honest, I'm not sure if the deref itself is the problem, or something else underlying. As you say, `g_object_unref` has been thread safe since GLib 2.8 - but only in the modification of the ref counter. It's not clear whether the finalizers are always thread safe, for example. Irrespective, something else might be going on.

However, with the hooks added in pr #820 it is possible to add support which fixes the problem. Since the hooks themselves doesn't change the behavior of the `gotk3` project, and it gives the possibility of solving the problem, I'm going to close this issue.

For anyone finding this later, this is the code we added to our large project to serialize deref-ing in the UI thread (note that this code uses the gotk3adapter interfaces, but the solution should be obvious anyway):
```
func registerFinalizerReaping(gl glibi.Glib) {
	fins := make(chan func(), finalizerBufferCapability)

	gl.SetFinalizerStrategy(func(f func()) {
		fins <- f
	})

	// This will ALWAYS be called in the UI thread
	finalizerPoller := func() bool {
		rounds := 0

		for rounds < finalizerPollRounds {
			select {
			case ff := <-fins:
				ff()
				rounds++
			default:
				return true
			}
		}

		return true
	}

	gl.TimeoutAdd(finalizerPollTime, finalizerPoller)
}
```

**Comment by awused** [comment]
This bug has misdiagnosed the problem. While forcing finalizers to run in the UI thread works to avoid some causes of this bug - by serializing everything in one thread - it does not fix all of them, because not all GTK/GDK/glib code runs in the main thread. Only UI activity needs to run inside the main thread, and the finalizer can still run while a Go struct is unreachable but the corresponding C struct is in use in another thread.

To demonstrate the problem using the SavePNG example from https://github.com/gotk3/gotk3/issues/797:

```
func (v *Pixbuf) SavePNG(path string, compression int) error {
	cpath := C.CString(path)
	ccompression := C.CString(strconv.Itoa(compression))
	defer C.free(unsafe.Pointer(cpath))
	defer C.free(unsafe.Pointer(ccompression))

	var err *C.GError
	c := C._gdk_pixbuf_save_png(v.native(), cpath, &err, ccompression)
	if !gobool(c) {
		defer C.g_error_free(err)
		return errors.New(C.GoString((*C.char)(err.message)))
	}
	return nil
}
```

Here it is rewritten slightly to show what is actually happening in the bug:
```
func (v *Pixbuf) SavePNG(path string, compression int) error {
	cpath := C.CString(path)
	ccompression := C.CString(strconv.Itoa(compression))
	defer C.free(unsafe.Pointer(cpath))
	defer C.free(unsafe.Pointer(ccompression))

	var err *C.GError
        native := v.native()
        // v is now unreachable and eligible for garbage collection
        // v's finalizer can free(native) right now in another thread.

	c := C._gdk_pixbuf_save_png(native, cpath, &err, ccompression)
	if !gobool(c) {
		defer C.g_error_free(err)
		return errors.New(C.GoString((*C.char)(err.message)))
	}
	return nil
}
```

After the call to v.native(), v is no longer referenced by SavePNG, and if the reference isn't reachable in the application code, v is eligible for garbage collection _even before SavePNG has returned_. This can cause the "native" object to be freed during the call to `gdk_pixbuf_save_png` The solution in this bug, of running all finalizers in the main thread, is not enough to prevent https://github.com/gotk3/gotk3/issues/797 if the application is running pixbuf code in a worker thread. My application ran pixbuf code in worker threads, so my application would still have been affected by this bug even with this fix.

Frankly I think the pull request should be reverted because it fails to address the bug.

**Comment by diamondburned** [comment]
I also agree that this pull request uglies the code a lot more than it should. I
don't know if there are any other fixes for that issue if this PR is reverted,
but it is very ugly.

As far as the rewritten code example goes, I'm fairly sure that by rewriting the
code as such, the code now violates the GC rules, and that the GC will try to
free `v` after rewriting the code as such, but not before. This is similar to
the Go `uintptr` casting of

```go
v := unsafe.Pointer(uintptr(unsafe.Pointer(v)) + 1) // ok

v1 := uintptr(unsafe.Pointer(v))
v1++
v2 := unsafe.Pointer(v1) // NOT ok
```

It's really hard to tell whether either case is true, though, because the way
gotk3 was written makes this pretty confusing. Either way, I think adding a `_ =
v` or `runtime.KeepAlive(v)` by the end of the function should make it clear.

**Comment by awused** [comment]
>I also agree that this pull request uglies the code a lot more than it should. I
don't know if there are any other fixes for that issue if this PR is reverted,
but it is very ugly.

The solution for this issue is the same, since it's the same bug with the same cause. I picked SavePNG because it's the case where I'd gotten bitten by it, but SavePNG is not a special case. Many functions in gotk3 are vulnerable to this, and they should include a `runtime.KeepAlive(v)` or equivalent whenever they call a C function.

>As far as the rewritten code example goes, I'm fairly sure that by rewriting the
code as such, the code now violates the GC rules, and that the GC will try to
free v after rewriting the code as such, but not before. 

While I don't consider myself an expert on the precise logic used by Go's GC, the uintptr example is an entirely different issue. It has nothing to do with unreachability and only to do with the fact that the stack can be resized (involving a move) and, in the future, Go may implement a compacting garbage collector. So an unsafe.Pointer() will remain valid, because Go considers it a pointer (a theoretical compacting GC would pin those values in the heap or something to that effect), but a uintptr is just an integer and no such guarantees are made for it.

Go's GC can be very aggressive with cleaning up Go structs. In fact, I believe v can be cleaned up before v.native() even returns, though it'd be vanishingly unlikely due to the triviality of the function.

**Comment by awused** [comment]
Also to be very clear, when I say "Many functions in gotk3 are vulnerable to this" I mean I think a majority of the functions on Go structs that manage C resources in gotk3 are memory-unsafe and can lead to segfaults. The reason you don't get more reports of segfaults is due to luck and circumstance more than anything.

Most widgets have refcounts incremented by GTK internally when you attach them to parents, so they get kept alive even if they're not reachable in Go code. It's also rare to call a method on an unattached widget and then do nothing with that widget (letting it become GC'd), not even attaching it to a parent, and detaching the widget is normally done as a final action before the application stops caring about it.

**Comment by diamondburned** [comment]
> While I don't consider myself an expert on the precise logic used by Go's GC, the uintptr example is an entirely different issue. It has nothing to do with unreachability and only to do with the fact that the stack can be resized (involving a move) and, in the future, Go may implement a compacting garbage collector.

This isn't true. By converting a pointer (e.g. `p`) to `uintptr` and not referencing that pointer in the future again, the GC will see that `p` is no longer used and will promptly free it. `uintptr` is just a number; the GC does not see it as an actual pointer, so it doesn't count as a reference towards `p`.
